### ISSUE TITLE
Initial requirements

### ISSUE THREAD

**Issue by rexim** [morganey-lang/morganey-gradle-plugin#1]
Derived from https://github.com/morganey-lang/Morganey/issues/238

We need to come up with initial minimal list of feature we wanna see in this project.

@ForNeVeR @06needhamt what do you guys think?

**Comment by rexim** [comment]
> ... that will package the *.mgn files in a standard Morganey format (be it *.jar or *.class or whatever)

Anything else? We can start with a simple prototype that does only this

**Comment by ForNeVeR** [comment]
How about that?

As a poor soul who tries to use Morganey in production, having a `build.gradle` like that:

``` gradle
plugins {
    id "me.rexim.morganey-gradle-plugin" version "0.0.1"
}

apply plugin: 'me.rexim.morganey-gradle-plugin'
```

and a project structure like that:

```
project
├src
│└main
│ └morganey
│  └package
│   └file.mgn
└build.gradle
```

I want the `gradle build` to produce the `build/libs/project.jar` with a following structure:

```
package
└file.mgn
```

**Comment by rexim** [comment]
What do you mean by `package`? Do you mean a Morganey module?

**Comment by ForNeVeR** [comment]
Yes.

**Comment by rexim** [comment]
Cool! I like this. Let me extract to a separate issue.

**Comment by rexim** [comment]
Alright the initial requirements are settled

**Comment by rexim** [comment]
@ForNeVeR thank you very much for spending your time on formalizing the requirements!
