### ISSUE TITLE
Harmonize gradlew versions

### ISSUE THREAD

**Issue by ForNeVeR** [morganey-lang/morganey-gradle-plugin#11]
For some reason our main project [uses gradle 3.1](https://github.com/morganey-lang/morganey-gradle-plugin/blob/992e943cc2968111c12c40eee0bcb0dcc0ba1ff2/gradle/wrapper/gradle-wrapper.properties#L6), but the test project [uses gradle 2.13](https://github.com/morganey-lang/morganey-gradle-plugin/blob/992e943cc2968111c12c40eee0bcb0dcc0ba1ff2/plugin-test/gradle/wrapper/gradle-wrapper.properties#L6).

I recommend to stick to 3.1 in both projects.

**Comment by 06needhamt** [comment]
@ForNeVeR Let me take a look at that
