### ISSUE TITLE
Publish the plugin to the Gradle plugin portal

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/morganey-gradle-plugin#17]
We should publish this plugin to the Gradle plugin portal as it would allow for more publicity and cleaner build scripts for our users. Documentation on publishing to the plugin portal can be found [here](https://plugins.gradle.org/docs/submit). I am more than happy to take this task on myself but i wanted to make sure you guys are OK with the idea first.

**Comment by ForNeVeR** [comment]
As I can see, this will allow our users to specify the plugin in their `build.gradle` and use it easily. That's very useful and should be done sooner or later, so, yeah, I'm totally okay with this.

**Comment by 06needhamt** [comment]
Ok then as both of you are happy with this i will go ahead and do this. One question though should i use my email to sign up for the portal or should we make an email address that is accessible to all morganey lang members so we can all access the account for receiving bug reports etc.

**Comment by ForNeVeR** [comment]
I think you can use your personal email for the initial submission, and later share the plugin project with @rexim. He'll take care of everything else.

**Comment by rexim** [comment]
@morganey-lang does not own any of its projects. All of the projects belong to their Project Leaders and they are responsiple for their maintainance. According to [Projects.md](https://github.com/morganey-lang/community/blob/45a219e2b00bed6f8d869a823a49f60d3e1976e4/Projects.md#morganey-gradle-plugin) @ForNeVeR is the Project Leader of `morganey-gradle-plugin`. So, following that logic we have to use his email. %)

It's a pretty complicated question that requires rules clarification. Let's just follow what @ForNeVeR suggested for now.

**Comment by ForNeVeR** [comment]
No problem, let's later share project with me, and I'll take care of everything else :)

**Comment by 06needhamt** [comment]
Its published but I'm not sure how to share it with anyone

**Comment by 06needhamt** [comment]
nvm i can give you my API key so you can publish to my account. Where should i post them too i don't feel comfortable posting them here

**Comment by ForNeVeR** [comment]
That's right, you should **never** post API keys or any sensitive credentials in public discussions. Please wait until tonight. I'll review your PR, register my own account at the Gradle plugin portal and take a closer look on how to share the project there.

Thank you for your time, I'll sort everything out soon!

_(tonight = approx. in 3 hours in my time zone)_

**Comment by ForNeVeR** [comment]
_(tonight = approx. in 3 hours in my time zone)_

**Comment by 06needhamt** [comment]
What time zone are you in it's 10AM here

**Comment by ForNeVeR** [comment]
We call it Barnaul/Gorno-Altaysk, it's UTC+7. Almost the same as @rexim (or even _the_ same if we don't account local time zone history and actual location).
