### ISSUE TITLE
Build Morganey project to jar

### ISSUE THREAD

**Issue by rexim** [morganey-lang/morganey-gradle-plugin#2]
Extracted from https://github.com/morganey-lang/gradle-morganey-plugin/issues/1#issuecomment-250974792

As a poor soul who tries to use Morganey in production, having a `build.gradle` like that:

``` gradle
plugins {
    id "me.rexim.morganey-gradle-plugin" version "0.0.1"
}

apply plugin: 'me.rexim.morganey-gradle-plugin'
```

and a project structure like that:

```
project
├src
│└main
│ └morganey
│  └package
│   └file.mgn
└build.gradle
```

I want the `gradle build` to produce the `build/libs/project.jar` with a following structure:

```
package
└file.mgn
```

**Comment by rexim** [comment]
@ForNeVeR hope you're ok with me replacing your `package` with `module`. :)

**Comment by rexim** [comment]
@06needhamt wanna work on that?

**Comment by 06needhamt** [comment]
@rexim Yes i am happy to work on that

**Comment by ForNeVeR** [comment]
@rexim could you please update the top post with my edited comment? I've made some important changes (you may avoid calling Morganey user a "poor soul" if you wish though 😄).

**Comment by rexim** [comment]
@ForNeVeR done! Thanks!

**Comment by rexim** [comment]
@06needhamt Alright, please feel free to start working on this when you feel ready. When you're done please submit a pull request to this repo for review and discussion. If you need any help, just ask. :) Thanks!

**Comment by 06needhamt** [comment]
Do I have write access or should i fork it?

**Comment by rexim** [comment]
@06needhamt you have write access to this repo. No need to fork it.

**Comment by 06needhamt** [comment]
OK i will take a look in the morning

**Comment by ForNeVeR** [comment]
But please consider changing the code using pull requests.

**Comment by 06needhamt** [comment]
See #3 for my progress so far

**Comment by 06needhamt** [comment]
see #10

**Comment by 06needhamt** [comment]
@ForNeVeR Can we close this now because #10 was merged?

**Comment by ForNeVeR** [comment]
Ah, sorry. Yes, we should!
