### ISSUE TITLE
Rename this repo to morganey-gradle-plugin to be consistant with morganey-intellij-plugin

### ISSUE THREAD

**Issue by 06needhamt** [morganey-lang/morganey-gradle-plugin#6]
Not totally necessary just one thing thats bugging me

**Comment by rexim** [comment]
Is there any officially approved naming scheme for gradle and intellij plugins? I called it `gradle-morganey-plugin` because I just opened https://github.com/gradle and saw this repo https://github.com/gradle/gradle-hazelcast-plugin and took it as a best practice. :)

**Comment by 06needhamt** [comment]
Ah i didn't know that we should probably leave it as it is then

**Comment by rexim** [comment]
Hm... Looks like at least for gradle there is nothing http://stackoverflow.com/questions/19452808/gradle-plugin-naming-convention

**Comment by 06needhamt** [comment]
@rexim I will leave it up to you and @ForNeVeR then

**Comment by rexim** [comment]
And for intellij I didn't find anything either.

**Comment by rexim** [comment]
@ForNeVeR what do you think?

I vote for `morganey-<platform>-plugin` for all of the plugin projects which platforms doesn't have a naming convention.

**Comment by 06needhamt** [comment]
Me Too

**Comment by rexim** [comment]
Because it's always better to put `morganey` first. :)

**Comment by 06needhamt** [comment]
It just makes more sense to me too because gradle-morganey-plugin to me sounds like a Morganey plugin for Gradle as in a plugin for the Morganey compiler not for Gradle

**Comment by ForNeVeR** [comment]
Yep, I vote for rename. Maven have a convention, indeed, but it's close to ours: `<xxx>-maven-plugin`. And Gradle don't have any.

**Comment by rexim** [comment]
Done. Thanks everyone!
